name: Docker Build and Publish

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=GPS Tracker application
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          tags: |
            ${{ github.event.release.prerelease == false && format('{0}/gps-tracker:latest', secrets.DOCKERHUB_USERNAME) || '' }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gps-tracker:${{ github.event.release.tag_name }}
